# Generated by Django 5.2.5 on 2025-09-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='catagory',
            field=models.CharField(choices=[('ALL', 'all'), ('IMPORTANT', 'Important'), ('BUSINESS', 'Business'), ('PERSONAL', 'Personal')], default='PERSONAL', max_length=15),
        ),
    ]
